### PR TITLE
[WIP] Taskfile support

### PR DESCRIPTION
**Pull request by HeCorr**
This PR implements support for [Task](https://taskfile.dev/), a cross-platform Make alternative written in Go.

See #2.

### CODE REVIEW

**Comment by HeCorr** [comment]
Unfortunately Task doesn't handle interrupt signals very well so I'm not sure if `watch.sh` is working properly:

image

I would have to test that with a custom executable but I don't think that's a priority, unless there's a chance of database corruption in the case of an unexpected shutdown. @thomiceli Please let me know if that's the case.

**Comment by HeCorr** [comment]
@thomiceli is this echo on line 33 correct?
https://github.com/thomiceli/opengist/blob/2951cb03f4d824c5feaf009dc0f7e381481142da/Makefile#L32-L34

**Comment by HeCorr** [comment]
As per c898285, the `watch.sh` script is no longer executed by Task, which has worked... better, but still not perfect:

image

At least now the backend seems to be properly shutting down, based on the `still waiting for 1 sub-process to finish` message.

It seems the `watch_frontend` failure error above is due to Vite returning exit code 1 when exiting with Ctrl+C/SIGINT. I did try to make it return 0 instead but that somehow caused the backend task to not exit properly... go figure.

**Comment by thomiceli** [comment]
> @thomiceli is this echo on line 33 correct?
> 
> https://github.com/thomiceli/opengist/blob/2951cb03f4d824c5feaf009dc0f7e381481142da/Makefile#L32-L34
> 
> If it's not please let me know what it's supposed to say instead and I'll fix it.

Indeed it's not correct, it should be something like "Running Opengist and watching for changes..."; same idea for `watch_frontend`

**Comment by HeCorr** [comment]
> EDIT : did not see you already changed it, all good!

I didn't yet, what I did was add descriptions but those don't get logged. I'll be fixing it soon

**Comment by HeCorr** [comment]
once again, my apologies for the inactivity. I've been quite busy.

**Comment by thomiceli** [comment]
Closing for now; maybe we can use a Taskfile in the future

**Pull request closed without merging**
