### PR TITLE
Add missing $ in templates

### LINKED ISSUE #116: Clicking gist "Revisions" tab causing 502 Bad Gateway
I am currently on the latest version of Opengist (v1.5.0). I was testing out private gists today and noticed the **revisions** tab which says I have two.

meuAF11

As soon as I click that link, the website automatically loads a 502 Bad Gateway for the url `https://gist.domain.com/username/0e36f42c247a56c1b224a4c2b16fd2ed/revisions` (this is all from a user computer).

I then connected to my server box using Remote Desktop and went to the website via `http://localhost:6157/`, signed in, went to the revisions tab and the server's browser leads me to a "This page cannot be reached" error.

CfdG3dU

Not sure what's going on, but the rest of the site seems to work fine. Only page I'm having issues with is the revisions tab.

### PR DESCRIPTION
**Pull request by thomiceli**
Should fix #116

### CODE REVIEW

**Comment by thomiceli** [comment]
@Aetherinox if possible, would you mind building the project from the branch (just run `make`) and tell me if you still have the 502 bad gateway error with your repository ?

**Comment by Aetherinox** [comment]
Sure, if you can give me just a quick series of steps. I've never ran from a different branch and not sure of the steps considering I have the existing version installed using docker.

**Comment by Aetherinox** [comment]
What a pain that was, I hate WSL2.

Yes, revisions seem to work great.

kJM3gKm

**Comment by thomiceli** [comment]
Perfect, thanks again

**Comment by Aetherinox** [comment]
@thomiceli Just tested v1.5.1, revisions works great now on productions server. Thanks.

**Pull request merged**
