### PR TITLE
Customise UID/GID

### LINKED ISSUE #57: customize UID/GID
Hello :D
It would be great to have the ability to customize the UID and GID via ENV.

### PR DESCRIPTION
**Pull request by thomiceli**
Closes #57 

Customise `UID` and `GID` by changing them via env vars

Also changed mount volume from `/root/.opengist` to `/opengist`

### CODE REVIEW

**Comment by thomiceli** [comment]
@Lyxon1337, @mariushosting Would you mind to build the Docker image and try if it could work out for you ?

**Comment by Lyxon1337** [comment]
oh sry forget it...
now i see u allready have this in the image! nice!
tested tag "1.3" and "latest = 1.4.0-dev"

On both i use your example compose from readme.
Both use the old mount path `/root/.opengist`? dunno (if i try the "new" one ->` /opengist` always failed.
Both start with given UID GID. But all data in the mapped Fodler are from host-root.
And also the created gist under "/repos" all created from host-root... So it's seems the UID/GID ENVs are not used here.

By the writting i have found a bug... But it's not the solution
it's a typo by the docker/entrypoint

u write:
```
export USER=opengist
PID=${PID:-1000}
GID=${GID:-1000}
groupmod -o -g "$GID" $USER
usermod -o -u "$PID" $USER
```
the `PID` is not the called readme `UID` :D
But even if i change the ENV from the compose the behavor not change at all (on both versions).

I'm pretty sure I'm forgetting something important

**Comment by mariushosting** [comment]
@thomiceli

**Comment by thomiceli** [comment]
> oh sry forget it... now i see u allready have this in the image! nice! tested tag "1.3" and "latest = 1.4.0-dev"
> 
> On both i use your example compose from readme. Both use the old mount path `/root/.opengist`? dunno (if i try the "new" one ->` /opengist` always failed. Both start with given UID GID. But all data in the mapped Fodler are from host-root. And also the created gist under "/repos" all created from host-root... So it's seems the UID/GID ENVs are not used here.
> 
> By the writting i have found a bug... But it's not the solution it's a typo by the docker/entrypoint
> 
> u write:
> 
> ```
> export USER=opengist
> PID=${PID:-1000}
> GID=${GID:-1000}
> groupmod -o -g "$GID" $USER
> usermod -o -u "$PID" $USER
> ```
> 
> the `PID` is not the called readme `UID` :D But even if i change the ENV from the compose the behavor not change at all (on both versions).
> 
> I'm pretty sure I'm forgetting something important

I missed the typo.. thanks i will fix it.
However I'm not sure why it fails for you, can you try by building the image yourself (`make build_docker`), I'm messing with the hosted images tags right now ? 
I will try again to launch an instance from v1.3 and then migrate into v1.4 to see if I encounter sort of bugs.

**Comment by Lyxon1337** [comment]
new test series :D
install via Portainer v2.18.3
I deleted all old images from opengist :)

Download again the tag `latest` after looking into the image details the Image layers 7 says `VOLUME [/root/.opengist]`
Download after this the tag `dev` and there the Volume is the righ
latest
t -> `VOLUME [/opengist]`
nice one :)

install test 1 with `latest` -> UID GID no function all is owned an create from host-root
i create u user and a test gist... User folder spawn into the `/repos` folder and all are from `root` (the mapped volume from compose `/volume1/docker/00-opengist:/root/.opengist:rw` )
latest

after delete all content and container :D
changed the volume to the new one -> `/volume1/docker/00-opengist:/opengist:rw`
create user and a test gist...
And.. ALL WORKED ! :D noice
dev

The data and the created files from the right choosen folder for compose :)
thanks for your fast work! :D

**Comment by thomiceli** [comment]
> new test series :D install via Portainer v2.18.3 I deleted all old images from opengist :)
> 
> Download again the tag `latest` after looking into the image details the Image layers 7 says `VOLUME [/root/.opengist]` Download after this the tag `dev` and there the Volume is the right -> `VOLUME [/opengist]` nice one :)
> 
> install test 1 with `latest` -> UID GID no function all is owned an create from host-root i create u user and a test gist... User folder spawn into the `/repos` folder and all are from `root` (the mapped volume from compose `/volume1/docker/00-opengist:/root/.opengist:rw` )
> 
> install test 2 with `dev` after delete all content and container :D changed the volume to the new one -> `/volume1/docker/00-opengist:/opengist:rw` create user and a test gist... And.. ALL WORKED ! :D noice dev
> 
> The data and the created files are from the choosen user from compose :) thanks for your fast work! :D

No problem :) Glad it worked !

**Pull request merged**
